Intelli-Holdings/intelli-chatbot

my-app/app/company/page.tsx
my-app/components/component/home.tsx

Worked on the Company Page, kindly check it out. thanks

Merge changes from Sika

---

my-app/components/component/pricing.tsx
my-app/components/component/resources.tsx

merge changes from Sila

---

my-app/app/api/chat/route.ts

Hello @silakironji the system prompt is declared here

reinstate route file

---

my-app/components/chat-window.tsx

Merge upstream changes

---

my-app/app/dashboard/conversations/elli/page.tsx
my-app/app/dashboard/conversations/page.tsx
my-app/components/component/home.tsx
my-app/constants/data.ts

1. remove some logos from brands
2. create conversations page
3. create elli page

merge changes from branch samson

---

my-app/app/api/chatbots/route.ts
my-app/app/api/whatsapp/[id]/route.ts
my-app/app/api/whatsapp/route.ts
my-app/app/dashboard/conversations/components/conversationsHeader.tsx
my-app/app/dashboard/conversations/components/conversationsList.tsx
my-app/app/dashboard/conversations/components/conversationsView.tsx
my-app/app/dashboard/conversations/components/messageHistory.tsx
my-app/app/dashboard/conversations/components/style.css
my-app/app/dashboard/conversations/elli/page.tsx
my-app/app/dashboard/conversations/page.tsx
my-app/app/dashboard/conversations/whatsapp/page.tsx
my-app/components/component/createChatbot.tsx
my-app/components/dashboard-nav.tsx
my-app/components/layout/header.tsx

- Added messages streaming from WhatsApp onto the dashboard. 
- Modify the lookout of message bubbles
- Change API endpoint for whatsapp messages

[PR]: Merge changes from branch Samson

---

my-app/app/dashboard/conversations/components/conversationsList.tsx
my-app/app/dashboard/conversations/components/conversationsView.tsx
my-app/app/dashboard/conversations/components/messageHistory.tsx
my-app/app/dashboard/reservations/page.tsx

I added a couple of features
1. Searchbar
2. Enabled sorting/ranking
3. Added scrollbar
4. Added viewport to messages
@silakironji please review and merge

[UI] Improve the visual feel and look of whatsapp conversations

---

my-app/app/dashboard/conversations/components/messageInput.tsx
my-app/app/dashboard/conversations/whatsapp/page.tsx

Merge changes from Samson

---

my-app/app/dashboard/conversations/components/conversationsView.tsx
my-app/app/dashboard/conversations/components/messageInput.tsx
my-app/components/component/dash.tsx
my-app/components/component/home.tsx
my-app/components/dash-components/stats.tsx
my-app/components/sections/preview-landing.tsx
my-app/components/video.tsx

This PR includes several updates and refinements:
- Added a local demo video file and created a video component to replace the previous YouTube video.
- Updated the cards' copy and adjusted the message input to a single field.
- Modified the conversations card to redirect users to the conversations tab.
- Commented out dummy stats and edited the conversations view for improved clarity and usability.

Update Video Component, Refine UI Elements, and Edit Conversations View

---

my-app/components/sections/preview-landing.tsx

I realized the video wasn't playing on the recently updated code when deployed but it plays on local so i switched to a dynamic link

modify preview landing component to show video from google drive

---

my-app/app/join-waitlist/page.tsx
my-app/components/component/cta-section.tsx
my-app/components/component/home.tsx
my-app/components/component/pricing-component.tsx
my-app/components/component/waitlist.tsx
my-app/components/component/whatsappSignup.tsx
my-app/components/home/howItworks.tsx
my-app/components/home/productSection.tsx
my-app/components/home/usecases.tsx
my-app/components/magicui/blur-in.tsx
my-app/components/magicui/magic-card.tsx
my-app/components/magicui/sparkles-text.tsx
my-app/components/testimonial.tsx
my-app/tailwind.config.ts

This PR includes several updates and new components added to enhance the landing page and overall user experience. 
Key changes are:
- Added a border beam to the Tailwind config.
- Created new sections: How It Works, Waitlist, Testimonials, Product, and Use Cases.
- Modified CTA and Pricing components.
- Introduced new components: Magic Card, Sparkles Text, Blur-in, and WhatsApp Signup.
- Updated wording on the Pricing component.

Feat: Added waitlist route 

---

my-app/components/casestudies.tsx
my-app/components/casestudy.tsx
my-app/components/component/popupModal.tsx
my-app/components/component/waitlist.tsx
my-app/components/home/usecases.tsx

- Increase time it takes for popup to show up to 60 seconds
- Modify copy on waitlist component
- Remove distinct shadow around waitlist form

Patch: Waitlist Popup

---

my-app/components/magicui/bento-grid.tsx

…
I removed unnecessary prop in BentoGrid causing build error

Refactor BentoCard component.

---

my-app/components/component/home.tsx
my-app/components/home/bentoSection.tsx
my-app/components/magicui/animated-beam-demo.tsx
my-app/components/magicui/bento-grid.tsx
my-app/components/magicui/hero-video-dialog.tsx
my-app/components/sections/preview-landing.tsx

This pull request includes a series of refactors across multiple components to enhance their functionality and appearance:
- **HeroVideoDialog**: Updated to use a default video source if no specific source is provided.
- **BentoCard**: Revised to update text color and remove unnecessary elements.
- **AnimatedBeamDemo**: Adjusted container height and realigned elements.
- **bentoSection**: Refined icons and descriptions for better clarity.
- **home**: Modified the landing page layout and integrated BentoSection component.
- **Benefits Section**: Improved overall design and content presentation.
These changes aim to streamline component functionality and improve the user interface.

Refactor Components and Improve Benefits Section

---

my-app/components/home/Footer.tsx
my-app/components/home/useCaseSection.tsx

Changes in this pull request
- added links to our social media (LinkedIn and IG) that were previously missing.
- changed copy on the CTA buttons in the use case section.

Fix: Copy and Functional Links

---

my-app/app/company/page.tsx
my-app/components/component/home.tsx
my-app/components/component/pricing.tsx
my-app/components/home/FAQcomponent.tsx
my-app/components/testimonial.tsx

This PR focuses on refining the overall design and content of the website for a more cohesive and user-friendly experience. Key changes I made include:
- Edited and streamlined copy on the pricing page for clarity and conciseness.
- Adjusted font sizes across the site for better readability.
- Reduced sharp border colors to create a more open, airy feel in the testimonial section.
- Aligned lettering and copy on the company page with the rest of the website’s style.
- Updated testimonial color gradient to teal.
- Changed FAQ section heading from blue to black for consistency.
- Added padding to the use cases section for improved spacing and layout.

Updates to Landing Page

---

my-app/app/dashboard/layout.tsx
my-app/components/magicui/sparkles-text.tsx

Error Fix: The build is successful now

---

my-app/app/api/chat/route.ts
my-app/app/chat/page.tsx
my-app/components/chat-window.tsx
my-app/package-lock.json
my-app/package.json

I changed the wrapper and everything is functional now..

Fix: Elli is back online

---

my-app/app/privacy/PrivacyPolicyClient.tsx
my-app/components/AnimatedText.tsx
my-app/package-lock.json
my-app/policies/EU.html
my-app/policies/Ghana.html
my-app/policies/Kenya.html
my-app/policies/USA.html

- [modified Privacy policy component for readability](https://github.com/Sqweya-AI/intelli-chatbot/commit/766e2579621e745b08422eaa95e6bfa9b394ea6b)
- [added address to the Privacy Policies](https://github.com/Sqweya-AI/intelli-chatbot/commit/5b4ea67df8b0fa084d11f68f3c3c5bfe52e71d2c)

update: made changes to Privacy Policy

---

my-app/app/terms-of-service/page.tsx
my-app/components/terms-of-service.tsx

Update: terms of service page

---

my-app/components/CreateOrganizationPopup.tsx
my-app/components/MyOrganizations.tsx

I made changes to the popup to display after 1000ms and also check local storage if user filled in form; 
Also changed the layout of table displaying organisations on Org page
Build runs successfully locally; it is merge-worthy

Fix: Create Organization Popup Show Frequency

---

my-app/app/dashboard/conversations/components/conversationsView.tsx
my-app/app/dashboard/conversations/components/message-bubble.css
my-app/app/dashboard/conversations/whatsapp/page.tsx
my-app/package-lock.json
my-app/package.json
my-app/utils/exportUtils.ts
my-app/utils/formatMessage.tsx

This PR introduces several improvements to the conversation view and message handling:  
- **Enhanced Message Bubble Styling**: Improved CSS for handling additional text types and refined date separator appearance.  
- **`formatMessage` Utility**: Added a new utility to streamline and enhance message formatting across the app.  
- **Full-Height Conversation View**: Set conversation view to occupy the full height for better usability.  
- **Export Utilities**: Integrated export options for conversations in PDF, CSV, and XLS formats using `jspdf`, `jspdf-autotable`, and `xlsx` dependencies.  
- **Autoscroll Functionality**: Added auto-scroll to the latest message for seamless user experience.  
- **Prop Handling**: Improved functionality by passing the `conversations` prop to the …

UI Chore:   Enhance Conversation View and added Export Functionality  

---

my-app/app/dashboard/conversations/components/conversationsHeader.tsx
my-app/app/dashboard/conversations/components/types.ts

refactor ConversationHeader to remove customerName state and use cust…

fix: Error in prod

---

my-app/components/Workground.tsx

This new PR has updates to ensure the widget creation form reflects updated backend requirements

Feat: Update widget creation Board

---

my-app/app/dashboard/conversations/website/page.tsx
my-app/components/Workground.tsx
my-app/components/app-sidebar.tsx

In this PR; changes include:
- Loading states for create widget button
- Upload avatar management
- Re-arranged items in sidenav
- New UI and feel for Widget creation

Feat: Revamped playground interface

---

my-app/components/Assistants.tsx
my-app/components/Workground.tsx

This PR has these changes:
1. modify API endpoint for widgets
2. remove extra edit button on assistants

Fix:Playground

---

my-app/components/Workground.tsx
my-app/components/create-assistant-dialog.tsx

1. change organizationId to organization_id in assistant creation form(to fit backend requirement)
2. modified API endpoint for fetching assistants on widget creation form

fix: create assistant

---

my-app/app/dashboard/layout.tsx
my-app/app/layout.tsx
my-app/components/Assistants.tsx
my-app/components/ToastProvider.tsx
my-app/components/Workground.tsx
my-app/components/create-assistant-dialog.tsx

- Added `ToastProvider` for centralized and customizable notifications.  
- Replaced `useToast` with `sonner` for consistent notifications in `Assistants`, `CreateAssistantDialog`, and `Workground` components.  
- Refactored notification logic to improve maintainability.

Feat: Added and Standardized Toast Notifications  

---

my-app/components/Assistants.tsx
my-app/components/Workground.tsx

This PR
- Enables users to update assistant details
- Enables users to delete created assistants
- Adds a sprinkle of **`magic`** in workground

feat: implement CRUD functionality for assistants

---

my-app/app/dashboard/conversations/components/conversationsHeader.tsx
my-app/app/dashboard/conversations/components/conversationsList.tsx
my-app/app/dashboard/conversations/components/conversationsView.tsx
my-app/app/dashboard/conversations/components/messageInput.tsx
my-app/app/dashboard/conversations/components/types.ts
my-app/app/dashboard/conversations/page.tsx
my-app/app/dashboard/conversations/whatsapp/page.tsx

**PR Title:** Enhance Conversations Page UI and Components
- Improved `ConversationHeader` to display customer names.
- Refactored `ConversationsList` for better search functionality.
- Added `phone number` prop to `ConversationView` and updated UI.
- Updated `MessageInput` to handle phone number prop and integrated improvements.
- Extended `ChatMessage` interface to include optional `customer_name`.
- Enhanced `WhatsappConvosPage` with error handling and phone number integration.

Feat: Replace customer number with customer name

---

my-app/components/WhatsappOnboarding.tsx
my-app/components/app-sidebar.tsx

1st Change; 
[feat: Reorder playground on sidebar](https://github.com/Intelli-Holdings/intelli-chatbot/commit/7862cdf48d898938ca082ed89623dec6365e1b41)
2nd Change
[feat: enhance WhatsApp onboarding with organization selection and alignmnent with Backend Fields](https://github.com/Intelli-Holdings/intelli-chatbot/commit/f926a9535efdd4a367561e1c0265991ba2cc37c8)

Fix: Whatsapp Manual Onboarding

---

my-app/app/layout.tsx
my-app/components/component/pricingcomponent.tsx
my-app/package-lock.json
my-app/package.json

This PR has a couple of changes
Change 1
[feat: add @aptabase/react dependency to project for analytics](https://github.com/Intelli-Holdings/intelli-chatbot/commit/c8b3d64cb053e8f0ddc50b7a1990a235a7802fc0)
Change 2:
[feat: integrate Google Analytics and Aptabase for enhanced tracking](https://github.com/Intelli-Holdings/intelli-chatbot/commit/900a3b4af1bfb62e949fa89f83af11720dbf8c80)
Change 3:
[update pricing to reflect new prices](https://github.com/Intelli-Holdings/intelli-chatbot/commit/ec653284163f9c1768b2642ee1f7ee44a5990020)
Change 4:
[fix: update pricing for WhatsApp Assistant to reflect new rates](https://github.com/Intelli-Holdings/intelli-chatbot/commit/df6dcad1c6f5d5741e10f424703222a87bc43df4)
Change 5:
[refactor: improve feature description in PricingComponent for …

Feat: Add new analytics providers

---

my-app/components/component/home.tsx
my-app/components/home/FAQcomponent.tsx
my-app/components/home/Footer.tsx
my-app/components/terms-of-service.tsx
my-app/policies/EU.html
my-app/policies/Ghana.html
my-app/policies/Kenya.html
my-app/policies/USA.html

This PR effects the changes below;
1. [fix: update company address and contact information in policy documents](https://github.com/Intelli-Holdings/intelli-chatbot/commit/a22f71635ed1aba8f04e44da321e8eae14c448b7)
2. [feat: redesign FooterComponent with updated layout and contact inform…](https://github.com/Intelli-Holdings/intelli-chatbot/commit/e09b0d5dca9943bf0a6621e36233ff1394e199cf) 
3. [fix: update registered address in Terms of Service for accuracy](https://github.com/Intelli-Holdings/intelli-chatbot/commit/8d0afb707e76bfcebe5f43bd90b9d3446bc28235)
4. [fix: replace FooterDemo with FooterComponent in Home component](https://github.com/Intelli-Holdings/intelli-chatbot/commit/e041cae8a7d8901aefc2f308b935c8a40427d065)
5. [fix: add border to FAQ component for improved …

Feat: Add New Office addresses to Website

---

my-app/app/dashboard/conversations/website/ChatMessages.tsx
my-app/app/dashboard/conversations/website/MessageFormatter.tsx
my-app/app/dashboard/conversations/website/page.tsx
my-app/components/chat-widget/chat-widget.tsx
my-app/components/user-nav.tsx
my-app/package-lock.json
my-app/package.json

This PR introduces several improvements:  
- Adds `dompurify` and `isomorphic-dompurify` for enhanced security in handling HTML content.  
- Introduces `ChatMessages` and `MessageFormatter` components for better chat message display and formatting.  
- Refactors the `UserNav` component for improved layout and accessibility.  
- Configures `marked` for synchronous rendering and ensures proper type handling.  
- Improves message display and Markdown content handling.

Enhance Security, Message Display, and Accessibility with New Components and Refactoring  

---

my-app/actions.ts
my-app/app/api/socket/route.ts
my-app/app/dashboard/conversations/components/conversationsHeader.tsx
my-app/app/dashboard/conversations/components/conversationsView.tsx
my-app/components/call-ui.tsx
my-app/hooks/use-call.ts
my-app/lib/webrtc.ts
my-app/package-lock.json
my-app/package.json
my-app/types/call.ts
my-app/types/socket.ts
my-app/utils/exportUtils.ts

This PR introduces several new features and improvements:  
- Adds `socket.io` and `socket.io-client` for real-time communication[WIP] to be implemented later.  
- Replaces XLSX export functionality with PDF and CSV options for contacts.  
- Integrates WebRTC tools and components to enable call functionality.  
- Enhances the conversation header with a dropdown menu to display customer number.

feat: Enhance Whatsapp Conversations Page, Export Options, and WebRTC Integration 

---

my-app/app/api/socket/route.ts
my-app/hooks/use-call.ts
my-app/lib/socket.ts

This PR introduces several improvements and refactorings:  
1. **Refactor Socket Handler:**  
- Migrated socket handling logic to use Next.js API routes for better integration and maintainability.  
- Improved connection and disconnection handling for sockets.  
2. **Update `useCall` Hook:**  
- Updated the `useCall` hook to dynamically use environment-specific API base URLs.  
- Ensured the hook uses the production API base URL in the production environment.  
3. **Add Socket Management Utility:**  
- Introduced a new utility for managing socket connections and disconnections, centralizing socket logic for reusability and cleaner code.  
These changes enhance the application's scalability, maintainability, and environment-specific configuration handling. …

fix: Solved build error related to socket api 

---

my-app/app/dashboard/assistants/page.tsx
my-app/app/dashboard/test.tsx
my-app/components/Assistants.tsx
my-app/components/ToastProvider.tsx
my-app/components/announcement.tsx
my-app/components/app-sidebar.tsx
my-app/components/assistants-new.tsx
my-app/components/component/dash.tsx
my-app/components/create-assistant-dialog.tsx
my-app/components/dashboard/main.tsx
my-app/components/delete-dialog-assistant.tsx
my-app/utils/tourSteps.ts

This PR introduces several UI/UX enhancements and fixes:  
- Added a close button to the `ToastProvider` component for better user control.  
- Refactored assistant deletion logic with improved error handling.  
- Enhanced dashboard styling with gradient backgrounds and futuristic layouts.  
- Created and integrated an announcement badge and banner into the sidebar.  
- Updated the dashboard background gradient for improved aesthetics.  
- Formatted and cleaned up the `CreateAssistantDialog` and `DeleteAssistantDialog` components.  
- Adjusted card transition durations and updated tour step positions for smoother interactions.

Feat: Enhance UI/UX of command center

---

my-app/components/assistants-new.tsx
my-app/components/delete-dialog-assistant.tsx

This PR has one function;
to enable users delete assistants. It shows you a beautiful popup to confirm if you want to delete assistant then proceeds to show you a toast notification upon successfully deleting assistant

dded delete assistant functionality 

---

my-app/app/dashboard/conversations/components/message-bubble.css
my-app/components/assistants-new.tsx
my-app/components/dashboard/main.tsx

This PR introduces several improvements to the user interface and backend functionality:  
- Standardized CSS for message bubbles to ensure consistent styling across the application.  
- Enhanced the assistant editing experience by adding loading states and error handling for a smoother user experience.  
- Updated API headers to include the `accept` method for JSON, enabling successful editing and data handling.  
- Adjusted the background color to blue for uniformity

Feat: Added delete functionality for assistants

---

my-app/app/dashboard/notifications/NotificationContainer.tsx
my-app/app/dashboard/notifications/page.tsx
my-app/app/dashboard/organization/[id]/page.tsx
my-app/app/dashboard/organization/page.tsx
my-app/app/globals.css
my-app/components/PhoneNumberForm.tsx
my-app/components/dash-components/stats.tsx
my-app/components/notification-assign-selector.tsx
my-app/components/notification-card.tsx
my-app/components/notifications-new.tsx
my-app/components/notifications.tsx
my-app/components/user-nav.tsx
my-app/components/widget-communication.tsx
my-app/data/testdata.ts
my-app/hooks/use-notification.ts
my-app/middleware.ts
my-app/package-lock.json
my-app/package.json
my-app/services/notifications.ts
my-app/tailwind.config.ts
my-app/types/notification.ts
my-app/types/notifications.ts
my-app/utils/members.ts

This PR introduces a comprehensive notification system, including WebSocket integration, notification types, and UI components for managing and displaying notifications. Key changes include:  
- Added `NotificationContainer`, `NotificationCard`, and `NotificationPage` components for streamlined notification handling.  
- Introduced `NotificationService` and `useNotifications` hook for managing WebSocket connections and notification assignments.  
- Added utility functions and types for transforming and handling team members, customers, and escalations.  
- Integrated `react-phone-number-input` for phone number input handling in the `PhoneNumberForm` component.  
- Refactored `ManageOrganizations` and `Stats` components for improved functionality and loading states. …

Feat: Enhance Notifications and Add Phone Number form.

---

my-app/components/Widgets.tsx
my-app/components/deployment-dialog.tsx

[fix: update widget API endpoints for organization-specific fetching](https://github.com/Intelli-Holdings/intelli-chatbot/commit/b118fe1e4f316305a51b3e389b0ee74f508b4172)
@[Samsonroyal](https://github.com/Intelli-Holdings/intelli-chatbot/commits?author=Samsonroyal)
Samsonroyal committed 2 hours ago
[fix: correct API endpoint for fetching embedding code in DeploymentDi…](https://github.com/Intelli-Holdings/intelli-chatbot/commit/5505ed5ff90f5cdabf202392a70a8ea097e70032)
This PR has the changes above; which are the new updated endpoints for widgets

Fix: Widgets display 

---

my-app/components/docs/theme-provider.tsx

refactor: enhance ThemeProvider component with additional props for improved theming control

fix: Build error

---

my-app/app/dashboard/conversations/page.tsx
my-app/app/layout.tsx
my-app/app/page.tsx
my-app/components/Widgets.tsx
my-app/components/conversations-website.tsx
my-app/components/deployment-dialog.tsx
my-app/hooks/use-organization-id.ts

This PR has the following key changes :  
- **SEO Improvements:**  
- Updated favicon links and enhanced metadata for better search engine optimization.  
- Removed unused `Head` component and associated metadata to clean up the codebase.  
- **Widget Component Refactoring:**  
- Created a new `WebsiteWidgetCard` component for displaying widget conversion data in a clean and reusable format.  
- Integrated `WebsiteWidgetCard` and refactored `StatsCards` for improved UI consistency and performance.  
- Added a link to website conversations for better navigation.  
- **Data Fetching Fixes:**  
- Updated API endpoints in `DeploymentDialog` and widget-related components to ensure correct data fetching.  
- Added a custom hook (`useActiveOrganizationId`) for retrieving …

Enable stats view on conversations page, and Improve Data Fetching Logic  

---

my-app/app/dashboard/conversations/page.tsx
my-app/app/dashboard/conversations/whatsapp/page.tsx
my-app/components/Widgets.tsx

This PR has changes made both to the `conversationsPage` and the `whatsappConvosPage` to replace the logic of fetching appservices by user email with organization id. All users in an organization are now able to access appservices

Feat: Add logic to fetch appservices by organization

---

my-app/app/dashboard/notifications/page.tsx
my-app/components/Widgets.tsx
my-app/components/notification-card.tsx
my-app/hooks/use-notification.ts
my-app/package-lock.json
my-app/package.json
my-app/services/notifications.ts

This PR includes:  
- Updated `posthog-js` to v1.217.0 for improved analytics.  
- Replaced deprecated `useOrganization` with `useActiveOrganizationId` across components.  
- Refactored notification service methods to use notification IDs and simplified member fetching.  
- Enhanced error handling and performance in notification workflows.  
- Reinstated the widgets page to restore missing functionality.

Feat: Update Dependencies, Refactor Hooks, and Enhance Notification Handling  

---

my-app/app/dashboard/conversations/website/page.tsx
my-app/hooks/use-website-conversations.ts

I changed the websocket url to a dynamic one

Fix: Error when sending reply on website conversations

---

my-app/app/api/organizations/route.ts
my-app/app/dashboard/conversations/components/conversationsView.tsx
my-app/app/dashboard/conversations/components/file-preview-carousel.tsx
my-app/app/dashboard/conversations/components/media-preview-dialog.tsx
my-app/app/dashboard/conversations/components/types.ts
my-app/app/dashboard/layout.tsx
my-app/app/layout.tsx
my-app/app/onboarding/confetti-effect.tsx
my-app/app/onboarding/onboarding-checklist.tsx
my-app/app/onboarding/onboarding-flow.tsx
my-app/app/onboarding/page.tsx
my-app/components/OnboardingReminder.tsx
my-app/components/ui/progress.tsx
my-app/components/workground-dialog.tsx
my-app/context/onboarding-context.tsx
my-app/services/organization.ts
services/organization.ts

This PR significantly improves our onboarding flow and adds robust media handling capabilities. Key changes include:
- Added dedicated onboarding context for state management
- Implemented guided checklist and progress tracking
- Created confetti effect for milestone celebrations
- Added user feedback collection during onboarding
- Simplified organization creation through the API
- Enhanced user flow with dynamic channel selection
- Made assistant creation optional in the onboarding flow
- Created media preview dialog for better file visualization
- Implemented file preview carousel for multiple attachments
- Refactored ConversationView with improved media handling
- Added attachments field to Conversation interface
- Updated Progress component styling
- Updated API base URL to use …

Feat: Add attachments viewing 

---

my-app/app/onboarding/onboarding-flow.tsx
my-app/app/onboarding/page.tsx
my-app/app/pre-onboarding/page.tsx
my-app/components/CreateOrganization.tsx
my-app/components/assistants-new.tsx
my-app/components/component/dynamic-heading.tsx
my-app/components/create-assistant-dialog.tsx

This PR introduces fixes to the onboarding flow and assistant creation process.
Key changes include:
1. **Onboarding Flow Improvements:**
- Added a pre-onboarding page for organization creation.
- Modified the create organization component to redirect to onboarding upon successful creation.
- Enhanced the onboarding flow for better seamlessness and clarity.
- Added a breadcrumb component to the onboarding screen for better navigation.
2. **Assistant Creation Enhancements:**
- Updated the assistant creation dialog to dynamically use organization IDs.
- Added an example prompt to the assistant creation process for better user guidance.
- Removed the dialog in favor of a more streamlined interface.
**Testing Instructions:**  
1. Create a new organization and verify …

Fix: Onboarding Flow with Organization and Assistant Creation 

---

my-app/app/dashboard/organization/[id]/page.tsx
my-app/components/assistant-files.tsx

This PR introduces a new "Files" tab in the organization settings page, allowing users to upload files or text content to their assistants. The `AssistantFiles` component handles file uploads, text input, and assistant selection, integrating with the backend API to update assistant files. Supported file types include PDF, DOC, DOCX, and TXT.

feat: Add files tab and component for assistant files in organization settings  

---

my-app/app/.well-known/microsoft-identity-association.json
my-app/app/dashboard/layout.tsx
my-app/components/assistants-new.tsx
my-app/components/chat-widget/chat-widget.tsx
my-app/components/edit-assistant-dialog.tsx

This PR introduces changes subtle but important in the long run:  
- Added Microsoft identity association configuration for authentication  
- Enhanced `ChatWidget` with new alert and avatar components  
- Improved `EditAssistantDialog` with better error handling and UI updates  
- Refactored `Assistants` component to use the updated edit dialog  
- Removed unused imports from `DashboardLayout` for cleaner code

Feat: Add Microsoft Identity Integration and decouple assistant management

---

my-app/components/comp-534.tsx
my-app/components/ui/timeline.tsx
my-app/components/websocket-handler.tsx

This pull request introduces a new Timeline component along with its supporting subcomponents to enhance the application's user interface for displaying chronological events. Additionally, it includes a fix for the WebSocketHandler component, correcting the WebSocket URL format to ensure proper connectivity and functionality. 
- **Timeline Component**: Added a new component for displaying a sequence of events.
- **Supporting Subcomponents**: Implemented necessary subcomponents to support the Timeline functionality.
- **WebSocketHandler Fix**: Corrected the WebSocket URL format to resolve connectivity issues.
This update aims to improve both the user experience and the reliability of real-time features in the application.

Add Timeline Component and Fix WebSocket URL Format

---

my-app/app/actions.ts
my-app/app/dashboard/notifications/page.tsx
my-app/components/websocket-handler.tsx
my-app/hooks/use-notification.ts

This PR addresses WebSocket connection issues and cleans up notification handling:  
- Updated fallback WebSocket URL to use production backend endpoint  
- Corrected WebSocket URL format in `useNotifications` hook  
- Removed disruptive toast notifications for connection events  
- Eliminated error toasts on WebSocket disconnection (now logs max reconnects instead)  
- Removed debug console logs from `NotificationPage` component

Fix: WebSocket Connection Toast errors and Notification Cleanup

---

my-app/app/onboarding/onboarding-flow.tsx
my-app/app/onboarding/page.tsx
my-app/components/AttentionBadge.tsx
my-app/components/assistants-new.tsx

This PR enhances UI components and onboarding functionality:  
- Refactored `AttentionBadge` to better handle favicon and notifications and appear less scary; it's subtle now 
- Improved assistant page with auto page reloads after using the edit/delete option dialogs to prevent page freeze  
- Enhanced onboarding flow with completion callback
- Corrected favicon image dimensions in `AttentionBadge`

Fix: Refactor Tab Badge & fix assistan page freeze bug

---

my-app/app/globals.css

> Added classes for app-sidebar border

Reinstate border color on app sidebar

---

my-app/app/dashboard/notifications/Notifications.tsx
my-app/components/WhatsappOnboarding.tsx
my-app/hooks/use-notification-context.tsx

This PR improves conversation handling and organization management:  
1. **Navigation Enhancements:**  
- Added direct navigation to conversations by channel type from notifications screen
- Implemented notification-based redirection to specific conversation channels  
2. **Organization Management:**  
- Auto-selects organization ID during manual WhatsApp onboarding

feat: Add navigation/redirection to right channel of conversations 

---

my-app/app/dashboard/conversations/components/messageInput.tsx
my-app/app/dashboard/conversations/website/page.tsx
my-app/app/layout.tsx
my-app/components/whatsapp-package.tsx

This PR includes the following updates:
* Improved metadata in layout files to boost SEO and enable more accurate search indexing.
* Introduced a new WhatsApp package component.
* Hid the audio icon/button in the message input component because it's not functional on the backend until it's ready for a cleaner UI.

Enhance SEO Metadata, Add WhatsApp Package component, and Hide Audio Button

---

my-app/app/api/notifications/assign/route.ts
my-app/app/blog/page.tsx
my-app/app/company/page.tsx
my-app/app/layout.tsx
my-app/app/page.tsx
my-app/app/pricing/page.tsx
my-app/package-lock.json
my-app/package.json

* Moved `ChatWidget` from layout file to client-facing pages for better control.
* Created API route to send emails when users are assigned notifications(Not yet implemented).
* Installed and configured Resend for email delivery.

Fix: App sidebar on dashboard

---

my-app/app/api/facebook/business-token/route.ts
my-app/app/api/facebook/direct-register/route.ts
my-app/app/api/facebook/exchange-token/route.ts
my-app/app/api/facebook/register-phone/route.ts
my-app/app/dashboard/channels/whatsapp/page.tsx
my-app/components/EmbeddedSignup.tsx
my-app/facebook-sdk.d.ts
my-app/tsconfig.json

**PR Description**:  
- Added TypeScript definitions for Facebook SDK integration  
- Updated tsconfig.json to include new type definitions  
- Implemented 4 new endpoints for Whatsapp ES flow
- Renamed WhatsApp channels page from "create whatsapp assistant" to "onboarding"  
- Improved EmbeddedSignup component state management for WhatsApp

Feat: Improve Embedded Signup Flow process

---

my-app/components/contacts.tsx
my-app/components/navbar.tsx
my-app/components/resolve-reminder.tsx
my-app/lib/api.ts

- Remove unused "place a call" button from contacts page
- Add link to Broadcasts Platform on navbar under products
- Update navbar link title for better clarity
- Configure API baseURL to use environment variables for improved deployment flexibility

feat: UI improvements and configuration updates

---

my-app/app/layout.tsx
my-app/app/whatsapp-api/page.tsx
my-app/app/whatsapp-broadcast/page.tsx
my-app/components/home/bentoSection.tsx
my-app/components/navbar.tsx

- Added WhatsApp API page with overview, comparison, pricing, and FAQ sections  
- Updated WhatsApp Broadcast page with refined headings and descriptions for clarity  
- Enhanced BentoSection to include WhatsApp API feature and renamed WhatsApp Broadcast  
- Added WhatsApp API link to the Products dropdown in the Navbar on the home page
- Updated metadata description

Feat: Add WhatsApp API page & Update Related Pages  

---

my-app/app/sitemap.ts
my-app/components/ChatWidget.tsx
my-app/public/llms.txt
my-app/public/robots.txt

This pull request introduces updates to the sitemap, external script URLs, and public files to enhance SEO, improve accessibility, and provide detailed documentation for the Intelli platform. The most important changes include adding new URLs to the sitemap, updating the script source in the `ChatWidget` component, and creating or modifying public files (`llms.txt` and `robots.txt`) to support platform documentation and crawler access.
* [`my-app/app/sitemap.ts`](diffhunk://#diff-f8a38e0f95512021de90e10274eee2d63cda5d989eba8d07e42968c2e0855f0cR85-R102): Added three new URLs (`/whatsapp-broadcast`, `/whatsapp-api`, and `/llms.txt`) to the sitemap with appropriate metadata to improve search engine visibility.
* [`my-app/components/ChatWidget.tsx`](diffhunk://#diff-18374703b5a37850c1e2bc5eba0 …

Feat: Improve LEO(LLM Rankings similar to SEO) and widget functionality

---

my-app/app/dashboard/conversations/page.tsx

Application error: a client-side exception has occurred (see the browser console for more information).

fix: correct phone number reference in conversation page

---

my-app/package.json

This pull request introduces a new dependency to the project. The main change is the addition of the `@t3-oss/env-nextjs` package to the `my-app/package.json` file, which will help with environment variable management in Next.js applications.
Dependency management:
* Added `@t3-oss/env-nextjs` version `^0.9.2` to the project dependencies in `package.json` to improve environment variable handling in the Next.js app.

feat: Add @t3-oss/env-nextjs dependency to package.json

---

my-app/app/api/whatsapp/upload-media/route.ts
my-app/components/create-template-form.tsx
my-app/components/customize-template-dialog.tsx
my-app/data/default-templates.ts
my-app/utils/template-creator.ts

This pull request introduces several improvements to the WhatsApp media upload API and the template creation flow. The main changes include enhanced validation and compliance for media uploads, a refactored and centralized template creation logic, and improved handling of media and variable examples in templates. Additionally, minor adjustments were made to default template texts to remove emojis.
**API and Media Upload Improvements**
- Added validation for allowed file types in the WhatsApp media upload API (`upload-media/route.ts`).
- Updated the upload session creation and file upload process to comply with the latest Meta API (v23.0), including proper query parameters and OAuth token formatting. [[1]](diffhunk://#diff-c98e467c868d41ffa179a14dd55c44e064a60a60def18b8fe9f60af443c71fb0R18- …

fix; Invalid parameter errors and upload media 

---

.idea/.gitignore
my-app/.gitignore
my-app/app/layout.tsx
my-app/components/consent-gate.tsx

This pull request solves two issues; unnecesary IDE files and handles Privacy Policy Compliance with meta pixel
IDE/editor configuration improvements:
* Added `.idea` and related IDE-specific files to `.gitignore` and `.idea/.gitignore` to prevent accidental commits of local IDE/editor configuration files. [[1]](diffhunk://#diff-21610973868a98feff98dd0460438a8a32cca1447bc8701537ec5048e0c5faebR1-R8) [[2]](diffhunk://#diff-fda9eabd5b520cb368eef8d1e5934fe6f324b5f629c8188f34f3a198e0ea3de8R42-R49)
Third-party script management:
* Removed Facebook tracking scripts from `my-app/app/layout.tsx` to avoid loading them before consent is given by user and moved their inclusion to the `ConsentGate` component for better control over when these scripts are loaded.

Fix Privacy compliance issues with meta pixel code

---

my-app/app/api/whatsapp/templates/route.ts
my-app/app/api/whatsapp/upload-media/route.ts
my-app/app/dashboard/templates/create/page.tsx
my-app/app/dashboard/templates/page.tsx
my-app/components/create-template-form.tsx
my-app/components/customize-template-dialog.tsx
my-app/components/test-message-dialog.tsx
my-app/utils/template-creator.ts

This PR introduces significant enhancements to media upload handling and WhatsApp template management:
* **Media Upload Improvements**
* Refactored to use `APP_ID` instead of WABA ID. This is what is required according to the META resumable upload API
* Enhanced error handling and logging for better reliability.
* Improved media handling during template creation.
* **Template Management Enhancements**
* Implemented API endpoints for WhatsApp template management.
* Added dynamic header media support for template creation.
* Updated redirect flow to templates list and removed redundant code.
* Renamed "Browse Templates" to "Default Templates" and introduced "Create Template" option.

Refactor Media Upload for Whatsapp templates & Add Template Management Features

---

my-app/app/dashboard/templates/page.tsx
my-app/components/app-service-credentials.tsx
my-app/components/broadcast-manager.tsx
my-app/components/carousel-template-creator.tsx
my-app/components/create-template-form.tsx
my-app/components/customize-template-dialog.tsx
my-app/components/flows-builder.tsx
my-app/components/flows-manager.tsx
my-app/components/flows-template-wrapper.tsx
my-app/components/test-message-dialog.tsx
my-app/data/default-templates.ts
my-app/types/flows.ts
my-app/utils/template-creator.ts

**Template Variable Handling Improvements:**
* Added support for extracting and managing variables in URL buttons, not just in the body and header, throughout the `CustomizeTemplateDialog` component and related logic. This ensures users are prompted to fill in all required variables, including those embedded in button URLs. 
* Updated the template customization validation to require all URL button variables to be filled before submission, improving error feedback and preventing incomplete template creation. (Fe0308faL329R377)
* Enhanced the `checkTemplateRequiresCustomization` logic to detect variables in button URLs, ensuring correct dialog prompting when customization is needed.
**Template Sending and Media Handling:**
* Refactored the `sendTestTemplate` function to support sending …

Enhance WhatsApp Template and Flow Management

---

my-app/components/carousel-template-creator.tsx
my-app/components/customize-template-dialog.tsx
my-app/components/flows-builder.tsx
my-app/components/flows-manager.tsx
my-app/components/flows-template-wrapper.tsx
my-app/components/ui/alert.tsx
my-app/data/default-templates.ts

This pull request significantly enhances the `CarouselTemplateCreator` component by adding robust support for template variables, improving validation, and refining the user experience for creating carousel templates. The main improvements include extracting and managing variables in message and card bodies, enforcing validation for variable examples, updating the UI to collect these examples, and restructuring the carousel data to match Meta's API requirements.
**Variable extraction & management:**
- Added logic to extract variables (e.g., `{{1}}`, `{{2}}`) from both the message body and each card's body text, storing their example values in state for use in template generation.
**Validation improvements:**
- Enhanced validation to require example values for all detected variables in …

Fix: Refactor code to fix default template Errors, Carousel and Flows Issues
